// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInstaller.Data.Context;

#nullable disable

namespace SmartInstaller.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726215821_RebuildCatalogSchema")]
    partial class RebuildCatalogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationTag", b =>
                {
                    b.Property<int>("SoftwareApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareApplicationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ApplicationTags", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoftwareApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SoftwareApplicationId");

                    b.ToTable("ApplicationVersions", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Browsers",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Slug = "browsers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Messaging",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Slug = "messaging"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Media",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Slug = "media"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Development",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000004"),
                            Slug = "development"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Utilities",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000005"),
                            Slug = "utilities"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Security",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000006"),
                            Slug = "security"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Compression",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000007"),
                            Slug = "compression"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Cloud Storage",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000008"),
                            Slug = "cloud-storage"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Microsoft Windows operating system",
                            IsActive = true,
                            Name = "Windows",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "windows"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Architectures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "x86",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "x64",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ARM64",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationVersionId")
                        .HasColumnType("int");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("InstallerTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresAdministrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("SilentInstallArguments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SilentUninstallArguments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("InstallerTypeId");

                    b.HasIndex("ApplicationVersionId", "InstallerTypeId", "ArchitectureId")
                        .IsUnique();

                    b.ToTable("InstallerProfiles", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InstallerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "EXE",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MSI",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MSIX",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ZIP",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationTag", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", "SoftwareApplication")
                        .WithMany("ApplicationTags")
                        .HasForeignKey("SoftwareApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Tag", "Tag")
                        .WithMany("ApplicationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareApplication");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", "SoftwareApplication")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareApplication");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Category", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Platform", "Platform")
                        .WithMany("Applications")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Publisher", "Publisher")
                        .WithMany("Applications")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Platform");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerProfile", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", "ApplicationVersion")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Installer.Architecture", "Architecture")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Installer.InstallerType", "InstallerType")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("InstallerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationVersion");

                    b.Navigation("Architecture");

                    b.Navigation("InstallerType");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Category", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Platform", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Publisher", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", b =>
                {
                    b.Navigation("ApplicationTags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Tag", b =>
                {
                    b.Navigation("ApplicationTags");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.Architecture", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerType", b =>
                {
                    b.Navigation("InstallerProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
