// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInstaller.Data.Context;

#nullable disable

namespace SmartInstaller.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805171440_SeedUpdateTestApplications")]
    partial class SeedUpdateTestApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationTag", b =>
                {
                    b.Property<int>("SoftwareApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareApplicationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ApplicationTags", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareApplicationId = 1,
                            TagId = 5
                        },
                        new
                        {
                            SoftwareApplicationId = 1,
                            TagId = 6
                        },
                        new
                        {
                            SoftwareApplicationId = 1,
                            TagId = 7
                        },
                        new
                        {
                            SoftwareApplicationId = 2,
                            TagId = 2
                        },
                        new
                        {
                            SoftwareApplicationId = 2,
                            TagId = 5
                        },
                        new
                        {
                            SoftwareApplicationId = 3,
                            TagId = 1
                        },
                        new
                        {
                            SoftwareApplicationId = 3,
                            TagId = 5
                        },
                        new
                        {
                            SoftwareApplicationId = 4,
                            TagId = 1
                        },
                        new
                        {
                            SoftwareApplicationId = 5,
                            TagId = 3
                        },
                        new
                        {
                            SoftwareApplicationId = 5,
                            TagId = 4
                        },
                        new
                        {
                            SoftwareApplicationId = 6,
                            TagId = 3
                        },
                        new
                        {
                            SoftwareApplicationId = 6,
                            TagId = 4
                        },
                        new
                        {
                            SoftwareApplicationId = 6,
                            TagId = 5
                        },
                        new
                        {
                            SoftwareApplicationId = 7,
                            TagId = 5
                        },
                        new
                        {
                            SoftwareApplicationId = 7,
                            TagId = 8
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoftwareApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SoftwareApplicationId", "Version")
                        .IsUnique();

                    b.ToTable("ApplicationVersions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLatest = true,
                            PublicId = new Guid("80000000-0000-0000-0000-000000000001"),
                            SoftwareApplicationId = 2,
                            Version = "3.0.23"
                        },
                        new
                        {
                            Id = 1002,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLatest = true,
                            PublicId = new Guid("80000000-0000-0000-0000-000000000002"),
                            SoftwareApplicationId = 6,
                            Version = "8.9.7"
                        },
                        new
                        {
                            Id = 1003,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsLatest = true,
                            PublicId = new Guid("80000000-0000-0000-0000-000000000003"),
                            SoftwareApplicationId = 7,
                            Version = "3.7.8"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Browsers",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Slug = "browsers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Messaging",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Slug = "messaging"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Media",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Slug = "media"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Development",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000004"),
                            Slug = "development"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Utilities",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000005"),
                            Slug = "utilities"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Security",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000006"),
                            Slug = "security"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Compression",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000007"),
                            Slug = "compression"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Cloud Storage",
                            PublicId = new Guid("40000000-0000-0000-0000-000000000008"),
                            Slug = "cloud-storage"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Microsoft Windows operating system",
                            IsActive = true,
                            Name = "Windows",
                            PublicId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "windows"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "Igor Pavlov",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Website = "https://www.7-zip.org"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "VideoLAN",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Website = "https://www.videolan.org"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "Mozilla",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Website = "https://www.mozilla.org"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "Google",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Website = "https://www.google.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "Microsoft",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000005"),
                            Website = "https://www.microsoft.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "Notepad++ Team",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000006"),
                            Website = "https://notepad-plus-plus.org"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsVerified = true,
                            Name = "Muse Group",
                            PublicId = new Guid("50000000-0000-0000-0000-000000000007"),
                            Website = "https://www.audacityteam.org"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("PlatformId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A file archiver with a high compression ratio.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "7-Zip",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000001"),
                            PublisherId = 1,
                            Slug = "7-zip",
                            Website = "https://www.7-zip.org"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A free and open-source multimedia player.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "VLC Media Player",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000002"),
                            PublisherId = 2,
                            Slug = "vlc-media-player",
                            Website = "https://www.videolan.org/vlc/"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A privacy-focused open-source web browser.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Mozilla Firefox",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000003"),
                            PublisherId = 3,
                            Slug = "mozilla-firefox",
                            Website = "https://www.mozilla.org/firefox/"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fast web browser developed by Google.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Google Chrome",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000004"),
                            PublisherId = 4,
                            Slug = "google-chrome",
                            Website = "https://www.google.com/chrome/"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A lightweight source code editor developed by Microsoft.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Visual Studio Code",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000005"),
                            PublisherId = 5,
                            Slug = "visual-studio-code",
                            Website = "https://code.visualstudio.com"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A free source code editor and Notepad replacement.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Notepad++",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000006"),
                            PublisherId = 6,
                            Slug = "notepad-plus-plus",
                            Website = "https://notepad-plus-plus.org"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A free, open-source multi-track audio editor and recorder.",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Audacity",
                            PlatformId = 1,
                            PublicId = new Guid("70000000-0000-0000-0000-000000000007"),
                            PublisherId = 7,
                            Slug = "audacity",
                            Website = "https://www.audacityteam.org"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Web browsing software",
                            IsActive = true,
                            Name = "Browser",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Slug = "browser"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Audio and video playback software",
                            IsActive = true,
                            Name = "Media Player",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000002"),
                            Slug = "media-player"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Software development tools",
                            IsActive = true,
                            Name = "Developer Tool",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000003"),
                            Slug = "developer-tool"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Source code editing software",
                            IsActive = true,
                            Name = "Code Editor",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000004"),
                            Slug = "code-editor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Open-source software",
                            IsActive = true,
                            Name = "Open Source",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000005"),
                            Slug = "open-source"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "File compression and extraction software",
                            IsActive = true,
                            Name = "Compression",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000006"),
                            Slug = "compression"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General system utility",
                            IsActive = true,
                            Name = "Utility",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000007"),
                            Slug = "utility"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Audio recording and editing software",
                            IsActive = true,
                            Name = "Audio Editor",
                            PublicId = new Guid("60000000-0000-0000-0000-000000000008"),
                            Slug = "audio-editor"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Architectures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "32-bit Windows architecture",
                            IsActive = true,
                            Name = "x86",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "64-bit Windows architecture",
                            IsActive = true,
                            Name = "x64",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "64-bit ARM architecture",
                            IsActive = true,
                            Name = "ARM64",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Architecture-independent installer",
                            IsActive = true,
                            Name = "Any",
                            PublicId = new Guid("20000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationVersionId")
                        .HasColumnType("int");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("InstallerTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPortable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresAdministrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SilentInstallArguments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SilentUninstallArguments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("InstallerTypeId");

                    b.HasIndex("ApplicationVersionId", "InstallerTypeId", "ArchitectureId")
                        .IsUnique();

                    b.ToTable("InstallerProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ApplicationVersionId = 1001,
                            ArchitectureId = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DownloadUrl = "https://get.videolan.org/vlc/3.0.23/win64/vlc-3.0.23-win64.exe",
                            FileSizeBytes = 45948080L,
                            InstallerTypeId = 1,
                            IsActive = true,
                            IsEnabled = true,
                            IsPortable = false,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000001"),
                            RequiresAdministrator = true,
                            Sha256 = "3b52a763a789562399f2e31063c9e545ca0ff28fa464e00b4af661fd62a6260d",
                            SilentInstallArguments = "/S"
                        },
                        new
                        {
                            Id = 1002,
                            ApplicationVersionId = 1001,
                            ArchitectureId = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DownloadUrl = "https://get.videolan.org/vlc/3.0.23/win32/vlc-3.0.23-win32.exe",
                            FileSizeBytes = 44568024L,
                            InstallerTypeId = 1,
                            IsActive = true,
                            IsEnabled = true,
                            IsPortable = false,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000002"),
                            RequiresAdministrator = true,
                            Sha256 = "0eef8f155f5fe6f70e9e1ad6c399cbeaaa1b3390b2281091ed1fb75f39fedae3",
                            SilentInstallArguments = "/S"
                        },
                        new
                        {
                            Id = 1003,
                            ApplicationVersionId = 1002,
                            ArchitectureId = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DownloadUrl = "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.7/npp.8.9.7.Installer.x64.exe",
                            FileSizeBytes = 6933184L,
                            InstallerTypeId = 1,
                            IsActive = true,
                            IsEnabled = true,
                            IsPortable = false,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000003"),
                            RequiresAdministrator = true,
                            Sha256 = "1884e093bae261c4942210334e1f2eae71354913e4ded3cc1a4a18c5320741ec",
                            SilentInstallArguments = "/S"
                        },
                        new
                        {
                            Id = 1004,
                            ApplicationVersionId = 1002,
                            ArchitectureId = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DownloadUrl = "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.7/npp.8.9.7.Installer.exe",
                            FileSizeBytes = 6788296L,
                            InstallerTypeId = 1,
                            IsActive = true,
                            IsEnabled = true,
                            IsPortable = false,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000004"),
                            RequiresAdministrator = true,
                            Sha256 = "9b89aa3221fdbce6ec2ee6f7d07de9fd7df2fbb7e7ce6d2f24e34ca347157dcf",
                            SilentInstallArguments = "/S"
                        },
                        new
                        {
                            Id = 1005,
                            ApplicationVersionId = 1003,
                            ArchitectureId = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DownloadUrl = "https://github.com/audacity/audacity/releases/download/Audacity-3.7.8/audacity-win-3.7.8-64bit.exe",
                            FileSizeBytes = 20400664L,
                            InstallerTypeId = 1,
                            IsActive = true,
                            IsEnabled = true,
                            IsPortable = false,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000005"),
                            RequiresAdministrator = true,
                            Sha256 = "4a6d77f023c0209a396fcf2f3c7c04e240b6ba9897b3231a6ed18e14c10caa16",
                            SilentInstallArguments = "/VERYSILENT /NORESTART"
                        },
                        new
                        {
                            Id = 1006,
                            ApplicationVersionId = 1003,
                            ArchitectureId = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DownloadUrl = "https://github.com/audacity/audacity/releases/download/Audacity-3.7.8/audacity-win-3.7.8-32bit.exe",
                            FileSizeBytes = 18940432L,
                            InstallerTypeId = 1,
                            IsActive = true,
                            IsEnabled = true,
                            IsPortable = false,
                            PublicId = new Guid("90000000-0000-0000-0000-000000000006"),
                            RequiresAdministrator = true,
                            Sha256 = "c0482d84a05ddd26905d010daff32b79eba18673489d2cb90ee87a386d24c74f",
                            SilentInstallArguments = "/VERYSILENT /NORESTART"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InstallerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Windows executable installer",
                            IsActive = true,
                            Name = "EXE",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Windows Installer package",
                            IsActive = true,
                            Name = "MSI",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Microsoft application package",
                            IsActive = true,
                            Name = "MSIX",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable compressed archive",
                            IsActive = true,
                            Name = "ZIP",
                            PublicId = new Guid("30000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationTag", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", "SoftwareApplication")
                        .WithMany("ApplicationTags")
                        .HasForeignKey("SoftwareApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Tag", "Tag")
                        .WithMany("ApplicationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareApplication");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", "SoftwareApplication")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareApplication");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Category", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Platform", "Platform")
                        .WithMany("Applications")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Catalog.Publisher", "Publisher")
                        .WithMany("Applications")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Platform");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerProfile", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", "ApplicationVersion")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Installer.Architecture", "Architecture")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Installer.InstallerType", "InstallerType")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("InstallerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationVersion");

                    b.Navigation("Architecture");

                    b.Navigation("InstallerType");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.ApplicationVersion", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Category", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Platform", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Publisher", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.SoftwareApplication", b =>
                {
                    b.Navigation("ApplicationTags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Catalog.Tag", b =>
                {
                    b.Navigation("ApplicationTags");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.Architecture", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Installer.InstallerType", b =>
                {
                    b.Navigation("InstallerProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
