// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInstaller.Data.Context;

#nullable disable

namespace SmartInstaller.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartInstaller.Core.Entities.ApplicationVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLatest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("SoftwareApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareApplicationId");

                    b.HasIndex("SoftwareApplicationId", "Version")
                        .IsUnique();

                    b.ToTable("ApplicationVersions", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Architectures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "32-bit Windows architecture",
                            IsActive = true,
                            Name = "x86"
                        },
                        new
                        {
                            Id = 2,
                            Description = "64-bit Windows architecture",
                            IsActive = true,
                            Name = "x64"
                        },
                        new
                        {
                            Id = 3,
                            Description = "64-bit ARM architecture",
                            IsActive = true,
                            Name = "ARM64"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Architecture-independent installer",
                            IsActive = true,
                            Name = "Any"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.InstallerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationVersionId")
                        .HasColumnType("int");

                    b.Property<int>("ArchitectureId")
                        .HasColumnType("int");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("InstallerTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequiresAdministrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("SilentInstallArguments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SilentUninstallArguments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationVersionId");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("InstallerTypeId");

                    b.HasIndex("ApplicationVersionId", "InstallerTypeId", "ArchitectureId")
                        .IsUnique();

                    b.ToTable("InstallerProfiles", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.InstallerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InstallerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Windows executable installer",
                            IsActive = true,
                            Name = "EXE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Microsoft Windows Installer package",
                            IsActive = true,
                            Name = "MSI"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern Microsoft application package",
                            IsActive = true,
                            Name = "MSIX"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Windows application package",
                            IsActive = true,
                            Name = "APPX"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Portable compressed application",
                            IsActive = true,
                            Name = "ZIP"
                        });
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.SoftwareApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("PublisherId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.ApplicationVersion", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.SoftwareApplication", "SoftwareApplication")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareApplication");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.InstallerProfile", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.ApplicationVersion", "ApplicationVersion")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("ApplicationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Architecture", "Architecture")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.InstallerType", "InstallerType")
                        .WithMany("InstallerProfiles")
                        .HasForeignKey("InstallerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationVersion");

                    b.Navigation("Architecture");

                    b.Navigation("InstallerType");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.SoftwareApplication", b =>
                {
                    b.HasOne("SmartInstaller.Core.Entities.Category", "Category")
                        .WithMany("Applications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInstaller.Core.Entities.Publisher", "Publisher")
                        .WithMany("Applications")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.ApplicationVersion", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Architecture", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Category", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.InstallerType", b =>
                {
                    b.Navigation("InstallerProfiles");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.Publisher", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("SmartInstaller.Core.Entities.SoftwareApplication", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
